### ISSUE TITLE
"package" is a reserved keyword linting error in v6.x.x

### ISSUE THREAD

**Issue by Aghassi** [sindresorhus/read-pkg-up#11]
Using `airbnb` + `prettier` for ESlinting, I can't destructure the way I use to when reading a package. I now get this linting error:

`Parsing error: The keyword 'package' is reserved`

Before I could do 

```js
const { pkg } = require('read-pkg-up').sync();
```

But as of v6 I can't do the following without the above error

```js
const { package } = require('read-pkg-up').sync();
```

Can `pkg` be left for backwards compatibility? Or is there a better recommended way of importing? I guess I can this?

```js
const { package: pkg } = require('read-pkg-up').sync();
```

Not sure why the property needed to be renamed, but just wanted to call out this issue in case others run into it.

**Comment by sindresorhus** [comment]
Ouch. I didn't think of destructuring when making that change... The reason I made that change is that I'm trying to use more readable variable names (no acronyms).

How about making it:

```js
const {packageJson} = require('read-pkg-up').sync();
```

?

**Comment by Aghassi** [comment]
@sindresorhus that's fine with me :).

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/read-pkg-up/releases/tag/v7.0.0
