### ISSUE TITLE
TypeScript typings issue

### ISSUE THREAD

**Issue by alexgorbatchev** [sindresorhus/read-pkg-up#12]
I'm having an issue with importing the packages after native types were introduces (vs `@types/read-pkg-up`. 
I've tried `import * as from` and `import ... = from`, same results for both using TypeScript 3.5.1

```
Object is possibly 'undefined'.ts(2532)
```

![image](https://user-images.githubusercontent.com/65633/59731300-67276f80-91fa-11e9-9714-d569a0b18a3b.png)

**Comment by sindresorhus** [comment]
I think the error message is pretty clear. `.pkg` can be `undefined` as it might not find a package.json file. You need to guard that somehow. If you're absolutely sure there's a package.json file there, you could do `readPkgUp.sync({cwd: fileName}).pkg!.name`, though it would not recommend it. I'm also confused by your naming of your argument `fileName` being passed to the `cwd` option, which expects a path to a directory.
