### ISSUE TITLE
Proposal:  change api

### ISSUE THREAD

**Issue by fisker** [sindresorhus/read-pkg-up#13]
You renamed `.package` in https://github.com/sindresorhus/read-pkg-up/commit/8140c731da0c4ddfedd549d55660acf0ee53ee1d .

But why not `readPkgUp` and `readPkgUp.sync` for the `json`, add `readPkgUp.resolve` and `readPkgUp.resolve.sync` to get the `path`, just like `require`

**Comment by sindresorhus** [comment]
What if you want both at the same time? Then it would have to search twice, which could also cause race conditions.

**Comment by fisker** [comment]
I would do `readPkgUp.resolve` get the path  then require or readjson

Just like I usually do with require, `require.resolve` then  require

**Comment by sindresorhus** [comment]
Then I would have to document how to use it properly and people will still not read it and do it wrong. With destructuring, the current API is fine, IMHO.

**Comment by fisker** [comment]
Sure, just suggestion.

**Comment by darkobits** [comment]
Another thing to consider here is that `read-pkg-up` [normalizes `package.json`](https://github.com/npm/normalize-package-data#what-normalization-currently-entails). You could run the results through [`normalize-package-data`](https://github.com/npm/normalize-package-data) yourself, but most developers won't think about this, resulting in more brittle programs. The decision to bake this into `read-pkg-up` was brilliant, and has spared developers the toil of having to understand the quirks of the `package.json` spec. 💯

**Comment by sindresorhus** [comment]
Another reason not to do it is that I just did two major versions for silly stuff, so I don't really want to cause more churn.
