### ISSUE TITLE
ESM module not working in Jest

### ISSUE THREAD

**Issue by djMax** [sindresorhus/read-pkg-up#22]
There are so very many moving parts. But after converting a project to ESM, I cannot run jest anymore for *this* package.

```
    Details:

    /oss/service/node_modules/read-pkg-up/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import path from 'node:path';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 |
      3 | import dotenv from 'dotenv';
    > 4 | import { readPackageUp } from 'read-pkg-up';
        | ^
      5 | import type { NormalizedPackageJson } from 'read-pkg-up';
```

You can see it fail here:
https://github.com/openapi-typescript-infra/service/tree/djmax/esm

I also can't eslint anymore, but one thing at a time. I'm mostly making the ESM move because you have so many packages and they are all ESM. I've tried a few times in the past year and failed each time. I'm hoping someone will have pity on me and perhaps I won't fail yet again.

**Comment by sindresorhus** [comment]
You should open an issue on Jest instead. This package is 100% correct ESM and the issue is not here.
