### ISSUE TITLE
Error from outdated `type-fest` version

### ISSUE THREAD

**Issue by pauliesnug** [sindresorhus/read-pkg-up#24]
I'm recieveing the `MergeDeep` recursion error using TypeScript `5.4.0`, which was fixed in the latest version of `type-fest`: https://github.com/sindresorhus/type-fest/pull/807, but all dependencies of read-package-up including read-pkg rely on an outdated `type-fest` version:

Output of `pnpm list type-fest --depth=100`:

```sh
dependencies:
read-package-up 11.0.0
├─┬ read-pkg 9.0.1
│ ├─┬ parse-json 8.1.0
│ │ └── type-fest 4.8.3
│ └── type-fest 4.8.3
└── type-fest 4.8.3
```

**Comment by sindresorhus** [comment]
All of these packages use semver specifiers that should get type-fest@4.12.0. This looks like a problem with pnpm or your lock file keeping old versions.

https://www.linkedin.com/pulse/understanding-semantic-versioning-guide-developers-ajibola-oseni-#:~:text=SemVer%20consists%20of%20three%20components,are%20introduced%20in%20the%20software.
