### ISSUE TITLE
Node 8.0.0 doesn't support object destructuring

### ISSUE THREAD

**Issue by rafamel** [sindresorhus/read-pkg-up#8]
Support for object destructuring was added by a minor Node@8 version. In order to support Node@8, which I would say is desirable, `Object.assign` must be used. This is an issue for this package, but also for its dependency `read-pkg`.

**Comment by sindresorhus** [comment]
It's expected that you upgrade minor Node.js versions. Those versions also come with important security fixes.

https://github.com/sindresorhus/meta/issues/8
